apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  API_BASE_URL: "http://example.local/api"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  JWT_SECRET: "change-me-very-secret"