#!/bin/bash

set -e  # Exit on error

echo "=========================================="
echo "K3s Network Security Lab - Prerequisites"
echo "=========================================="
echo ""

# =============================================================================
# Privilege Check
# =============================================================================
echo "Checking privileges..."
if ! sudo -v 2>/dev/null; then
  echo "Error: This script requires sudo privileges."
  echo "Please ensure your user has sudo access and try again."
  exit 1
fi
echo "  Sudo privileges verified."

# Keep sudo timestamp alive during long operations
while true; do sudo -n true; sleep 60; kill -0 "$$" 2>/dev/null || exit 0; done 2>/dev/null &
SUDO_KEEPALIVE=$!
trap "kill $SUDO_KEEPALIVE 2>/dev/null" EXIT

# Preserve user's HOME and original user info
ORIGINAL_USER="$SUDO_USER"
if [ -z "$ORIGINAL_USER" ]; then
  ORIGINAL_USER="$(whoami)"
fi
ORIGINAL_HOME="/home/$ORIGINAL_USER"

echo "  Running as user: $ORIGINAL_USER"
echo ""

# =============================================================================
# FQDN Configuration
# =============================================================================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_DIR/.lab-config"

# Load existing config if available
if [ -f "$CONFIG_FILE" ]; then
  source "$CONFIG_FILE"
fi

echo "=========================================="
echo "Lab FQDN Configuration"
echo "=========================================="
echo ""
echo "Enter the FQDN for your lab environment."
echo "This will be used for TLS certificates, /etc/hosts,"
echo "Ingress routing, and all service URLs."
echo ""

# Prompt for FQDN with default value
read -p "Lab FQDN [demo.testlab.lan]: " USER_FQDN
LAB_FQDN="${USER_FQDN:-demo.testlab.lan}"

# Validate FQDN format (basic check: contains at least one dot, no spaces)
if [[ "$LAB_FQDN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?\.[a-zA-Z]{2,}$ ]] || [[ "$LAB_FQDN" =~ ^[a-zA-Z0-9_-]+\.[a-zA-Z]{2,}$ ]]; then
  echo "  FQDN set to: $LAB_FQDN"
else
  echo "  Warning: '$LAB_FQDN' may not be a valid FQDN format."
  read -p "Continue anyway? (y/N): " CONFIRM
  if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
  fi
  echo "  FQDN set to: $LAB_FQDN (user override)"
fi

# Save configuration
cat > "$CONFIG_FILE" <<EOF
# Lab configuration file - auto-generated by install_prerequisites.sh
# Do not edit manually unless you know what you are doing.
LAB_FQDN="$LAB_FQDN"
EOF

echo "  Configuration saved to $CONFIG_FILE"
echo ""

# =============================================================================
# Step 1: Update package lists
# =============================================================================
echo "[1/6] Updating package lists..."
sudo apt-get update -y
echo "  Package lists updated."
echo ""

# =============================================================================
# Step 2: Install system dependencies
# =============================================================================
echo "[2/6] Installing system dependencies..."
sudo apt-get install -y \
  curl \
  wget \
  iptables \
  jq \
  openssl \
  ca-certificates \
  fuse-overlayfs \
  git \
  uidmap
echo "  System dependencies installed."
echo ""

# =============================================================================
# Step 3: Install runc (OCI Container Runtime)
# =============================================================================
echo "[3/6] Installing runc..."

if command -v runc &> /dev/null; then
  echo "  runc already installed: $(runc --version 2>/dev/null | head -1)"
else
  echo "  Installing runc from GitHub releases..."
  RUNC_VERSION="1.1.12"  # Stable release
  curl -L -o /tmp/runc.amd64 "https://github.com/opencontainers/runc/releases/download/v${RUNC_VERSION}/runc.amd64"
  sudo install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc
  rm -f /tmp/runc.amd64
  echo "  runc installed: $(runc --version 2>/dev/null | head -1)"
fi
echo ""

# =============================================================================
# Step 4: Install CNI Plugins
# =============================================================================
echo "[4/6] Installing CNI plugins..."

CNI_PLUGINS_DIR="/opt/cni/bin"
if [ ! -d "$CNI_PLUGINS_DIR" ] || [ -z "$(ls -A $CNI_PLUGINS_DIR 2>/dev/null)" ]; then
  echo "  Installing CNI plugins..."
  sudo mkdir -p "$CNI_PLUGINS_DIR"
  
  CNI_VERSION="1.4.0"
  curl -L "https://github.com/containernetworking/plugins/releases/download/v${CNI_VERSION}/cni-plugins-linux-amd64-v${CNI_VERSION}.tgz" | \
    sudo tar -C "$CNI_PLUGINS_DIR" -xz
  
  echo "  CNI plugins installed to $CNI_PLUGINS_DIR"
  ls "$CNI_PLUGINS_DIR" | head -5 | sed 's/^/    /'
  echo "    ... and more"
else
  echo "  CNI plugins already installed in $CNI_PLUGINS_DIR"
fi
echo ""

# =============================================================================
# Step 5: Install rootlesskit and slirp4netns
# =============================================================================
echo "[5/6] Installing rootlesskit and slirp4netns..."

# Install rootlesskit from GitHub releases
if ! command -v rootlesskit &> /dev/null; then
  echo "  Installing rootlesskit..."
  ROOTLESSKIT_VERSION="2.1.0"
  curl -L -o /tmp/rootlesskit "https://github.com/rootless-containers/rootlesskit/releases/download/v${ROOTLESSKIT_VERSION}/rootlesskit-$(uname -m)"
  sudo install -m 755 /tmp/rootlesskit /usr/local/bin/rootlesskit
  rm -f /tmp/rootlesskit
  echo "  rootlesskit installed."
else
  echo "  rootlesskit already installed."
fi

# Install slirp4netns from GitHub releases
if ! command -v slirp4netns &> /dev/null; then
  echo "  Installing slirp4netns..."
  SLIRP4NETNS_VERSION="1.3.1"
  curl -L -o /tmp/slirp4netns "https://github.com/rootless-containers/slirp4netns/releases/download/v${SLIRP4NETNS_VERSION}/slirp4netns-$(uname -m)"
  sudo install -m 755 /tmp/slirp4netns /usr/local/bin/slirp4netns
  rm -f /tmp/slirp4netns
  echo "  slirp4netns installed."
else
  echo "  slirp4netns already installed."
fi
echo ""

# =============================================================================
# Step 6: Configure sysctl for networking
# =============================================================================
echo "[6/6] Configuring network sysctl parameters..."

# Enable IP forwarding and bridge netfilter
sudo tee /etc/sysctl.d/99-k8s-net.conf > /dev/null <<EOF
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# Apply sysctl settings (ignore errors if modules not loaded yet)
sudo sysctl --system 2>/dev/null || echo "  Warning: Some sysctl settings could not be applied"

# Load required kernel modules
sudo modprobe overlay 2>/dev/null || true
sudo modprobe br_netfilter 2>/dev/null || true

# Ensure modules load on boot
sudo tee /etc/modules-load.d/k8s.conf > /dev/null <<EOF
overlay
br_netfilter
EOF

echo "  Network sysctl parameters configured."
echo ""

# =============================================================================
# Summary
# =============================================================================
echo "=========================================="
echo "Prerequisites Installation Complete!"
echo "=========================================="
echo ""
echo "Installed components:"
echo "  - runc (OCI container runtime)"
echo "  - CNI plugins (networking)"
echo "  - rootlesskit (rootless containers)"
echo "  - slirp4netns (rootless networking)"
echo "  - fuse-overlayfs (overlay filesystem)"
echo "  - iptables (network rules)"
echo ""
echo "Configured FQDN: $LAB_FQDN"
echo ""
echo "Next step:"
echo "  ./scripts/install_k3s.sh"
echo ""
echo "Note: A system reboot is recommended to apply all kernel module changes."
echo "=========================================="
